export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}

export const MESSAGES = {
  USER_ALREADY_EXISTS: "User already exists",
  INVALID_CREDENTIALS: "Invalid credentials",
  SERVER_ERROR: "Server error",
  UNAUTHORIZED: "Unauthorized",
  USER_NOT_FOUND: "User not found",
  ALL_FIELDS_REQUIRED: "All fields are required.",
  PASSWORD_MIN_LENGTH: "Password must be at least 8 characters long.",
  PASSWORDS_DO_NOT_MATCH: "New passwords do not match.",
  CURRENT_PASSWORD_INCORRECT: "Current password is incorrect.",
  PROFILE_UPDATED: "Profile updated successfully",
  PASSWORD_UPDATED: "Password updated successfully.",
  LOGGED_OUT: "Logged out successfully",
  TITLE_MIN_LENGTH: "Title must be at least 3 characters long.",
  ONLY_IMAGES_ALLOWED: "Only image files are allowed.",
  NO_UPDATE_FIELDS: "No update fields provided.",
  ARTICLE_NOT_FOUND: "Article not found",
  UNAUTHORIZED_ARTICLE_EDIT: "Unauthorized to edit this article",
  UNAUTHORIZED_ARTICLE_DELETE: "Unauthorized to delete this article",
  ARTICLE_DELETED: "Article deleted successfully",
  INVALID_ACTION: "Invalid action",
  ARTICLE_ID_MISSING: "articleId missing",
  PREFERENCES_UPDATED: "Preferences updated successfully",
};